### REGISTRO
POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
  "username": "exampleuser",
  "email": "user@example.com",
  "password": "12345678"
}



### LOGIN
POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "12345678"
}






### VERIFICAR TOKEN
GET http://127.0.0.1:8000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnZW5lcmljb0BleGFtcGxlLmNvbSIsImV4cCI6MTc2NDY1MjgxMX0.RQcJ7ga17MHpAUyEbEBcbhTgjBL9rvWfiL37ekkXhIE


### CREAR POST
POST http://127.0.0.1:8000/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnZW5lcmljb0BleGFtcGxlLmNvbSIsImV4cCI6MTc2NDgyMTk4Mn0.n3r9weJdIxweExHqmcQ_7vdlc1Z1CTlfQ85Hiz0nZzw
Content-Type: application/json

{
  "title": "Nueva post , prueba v3 ",
  "content": "Hola a todos como estan!"
}

### OBTENER POSTS
GET http://localhost:8000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwcnVlYmFAZXhhbXBsZS5jb20iLCJleHAiOjE3NjQ2NTM1NTd9.YZTS029fDX4fbCg5WBZVBoGGCzoIDaK8USDQ3saGn0M


### obtener post por id
GET http://localhost:8000/posts/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnZW5lcmljb0BleGFtcGxlLmNvbSIsImV4cCI6MTc2NDY1MjgxMX0.RQcJ7ga17MHpAUyEbEBcbhTgjBL9rvWfiL37ekkXhIE


### EDITAR POST
PUT http://localhost:8000/posts/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnZW5lcmljb0BleGFtcGxlLmNvbSIsImV4cCI6MTc2NDY1MjgxMX0.RQcJ7ga17MHpAUyEbEBcbhTgjBL9rvWfiL37ekkXhIE
Content-Type: application/json

{
  "title": "Post Nuevo",
  "content": "Contenido editado x2"
}


### BORRAR POST
DELETE http://localhost:8000/posts/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnZW5lcmljb0BleGFtcGxlLmNvbSIsImV4cCI6MTc2NDY1MjgxMX0.RQcJ7ga17MHpAUyEbEBcbhTgjBL9rvWfiL37ekkXhIE
