### REGISTRO
POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
  "username": "exampleuser",
  "email": "user@example.com",
  "password": "12345678"
}



### LOGIN
POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "12345678"
}






### VERIFICAR TOKEN
GET http://127.0.0.1:8000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnZW5lcmljb0BleGFtcGxlLmNvbSIsImV4cCI6MTc2NTQzMzE0MX0.4HN6UJHk7xsbQLLRwxYvKzJ9xlH1KK_c-yhgoMC0FBg


### CREAR POST
POST http://127.0.0.1:8000/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnZW5lcmljb0BleGFtcGxlLmNvbSIsImV4cCI6MTc2NTQzNTI4MH0.2xFMIizknhkXaoLVQdnRIzIJBsp2BOBcMeqsS-btC7Y
Content-Type: application/json

{
  "title": "Proyecto Python dev",
  "content": "devCommunity es lo mejor"
}

### OBTENER POSTS
GET http://localhost:8000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnZW5lcmljb0BleGFtcGxlLmNvbSIsImV4cCI6MTc2NTQzNTI4MH0.2xFMIizknhkXaoLVQdnRIzIJBsp2BOBcMeqsS-btC7Y


### obtener post por id
GET http://localhost:8000/posts/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnZW5lcmljb0BleGFtcGxlLmNvbSIsImV4cCI6MTc2NTQzNTI4MH0.2xFMIizknhkXaoLVQdnRIzIJBsp2BOBcMeqsS-btC7Y


### EDITAR POST
PUT http://localhost:8000/posts/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzY1NDM1NjEzfQ.HXLPSca64wq4zx2uzpKTDoE5hg2fVRn_X7VHat1MKK4
Content-Type: application/json

{
  "title": "Post Nuevo",
  "content": "Contenido editado x2"
}


### BORRAR POST
DELETE http://localhost:8000/posts/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnZW5lcmljb0BleGFtcGxlLmNvbSIsImV4cCI6MTc2NTQzNTI4MH0.2xFMIizknhkXaoLVQdnRIzIJBsp2BOBcMeqsS-btC7Y


