### Like post
POST http://localhost:8000/posts/6/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnZW5lcmljb0BleGFtcGxlLmNvbSIsImV4cCI6MTc2NjAwNjMwNn0.cKvEcnJpsZm4mi1pj5YLUCcMfiJ2iCf8MBzYuBQ1YM8

### Unlike post
DELETE http://localhost:8000/posts/1/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnZW5lcmljb0BleGFtcGxlLmNvbSIsImV4cCI6MTc2NjAwNjMwNn0.cKvEcnJpsZm4mi1pj5YLUCcMfiJ2iCf8MBzYuBQ1YM8

### Get posts
GET http://localhost:8000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnZW5lcmljb0BleGFtcGxlLmNvbSIsImV4cCI6MTc2NjAwNjMwNn0.cKvEcnJpsZm4mi1pj5YLUCcMfiJ2iCf8MBzYuBQ1YM8
