### Like post
POST http://localhost:8000/posts/1/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwcnVlYmFAZXhhbXBsZS5jb20iLCJleHAiOjE3NjY4OTc0Njh9.jU440JrtBYIm1bHYLHzT_MmxcGALoNyQNzysI_hb1YU

### Unlike post
DELETE http://localhost:8000/posts/1/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzY2NzA5MzkzfQ.BYfjSRYw1M0qUCODj_MC9kCNauDrIw2-rc9D8JZPYi0

### Get posts
GET http://localhost:8000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzY2NzA5MzkzfQ.BYfjSRYw1M0qUCODj_MC9kCNauDrIw2-rc9D8JZPYi0